syntax = "proto3";

package audimus;

enum SESSION_MODE{
   ConnectionlessDownlink =0;
   ConnectedDownlink = 1;
   ConnectedUplink = 2;
}

message Application_Message{
  string message = 1;
}

message Presentation_Message{
  int32 key_epoch = 1;
  int32 session_number = 2;
  bytes application_message = 3;
  bytes authentication_tag = 4;
}

message Session_Message{
  SESSION_MODE mode = 1;
  optional int32 packet_number =2;
  bytes presentation_message = 3;
  optional bool SYN = 4 ;
  optional bool SYNACK = 5;
  optional bool ACK = 6;
  optional bool DATA = 7;
  optional bool DATAREQ= 8;
  optional bool NACK = 9;
  optional bool FIN = 10;
  repeated uint32 missing_packets = 11;
}