# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Audimus.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'Audimus.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rAudimus.proto\x12\x07\x61udimus\"K\n\x13\x41pplication_Message\x12\x0f\n\x07message\x18\x01 \x01(\t\x12#\n\x04type\x18\x02 \x01(\x0e\x32\x15.audimus.MESSAGE_TYPE\"z\n\x14Presentation_Message\x12\x11\n\tkey_epoch\x18\x01 \x01(\x05\x12\x16\n\x0esession_number\x18\x02 \x01(\x05\x12\x1b\n\x13\x61pplication_message\x18\x03 \x01(\x0c\x12\x1a\n\x12\x61uthentication_tag\x18\x04 \x01(\x0c\"\x80\x03\n\x0fSession_Message\x12#\n\x04mode\x18\x01 \x01(\x0e\x32\x15.audimus.SESSION_MODE\x12\x1a\n\rpacket_number\x18\x02 \x01(\x05H\x00\x88\x01\x01\x12\x1c\n\x14presentation_message\x18\x03 \x01(\x0c\x12\x10\n\x03SYN\x18\x04 \x01(\x08H\x01\x88\x01\x01\x12\x13\n\x06SYNACK\x18\x05 \x01(\x08H\x02\x88\x01\x01\x12\x10\n\x03\x41\x43K\x18\x06 \x01(\x08H\x03\x88\x01\x01\x12\x11\n\x04\x44\x41TA\x18\x07 \x01(\x08H\x04\x88\x01\x01\x12\x14\n\x07\x44\x41TAREQ\x18\x08 \x01(\x08H\x05\x88\x01\x01\x12\x11\n\x04NACK\x18\t \x01(\x08H\x06\x88\x01\x01\x12\x10\n\x03\x46IN\x18\n \x01(\x08H\x07\x88\x01\x01\x12\x10\n\x03RET\x18\x0b \x01(\x08H\x08\x88\x01\x01\x12\x1a\n\x12retransmit_request\x18\x0c \x03(\rB\x10\n\x0e_packet_numberB\x06\n\x04_SYNB\t\n\x07_SYNACKB\x06\n\x04_ACKB\x07\n\x05_DATAB\n\n\x08_DATAREQB\x07\n\x05_NACKB\x06\n\x04_FINB\x06\n\x04_RET*V\n\x0cSESSION_MODE\x12\x1a\n\x16\x43onnectionlessDownlink\x10\x00\x12\x15\n\x11\x43onnectedDownlink\x10\x01\x12\x13\n\x0f\x43onnectedUplink\x10\x02*V\n\x0cMESSAGE_TYPE\x12\x0b\n\x07\x43ommand\x10\x00\x12\x14\n\x10\x43ommand_response\x10\x01\x12\x11\n\rSonobuoy_data\x10\x02\x12\x10\n\x0cMission_data\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Audimus_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SESSION_MODE']._serialized_start=614
  _globals['_SESSION_MODE']._serialized_end=700
  _globals['_MESSAGE_TYPE']._serialized_start=702
  _globals['_MESSAGE_TYPE']._serialized_end=788
  _globals['_APPLICATION_MESSAGE']._serialized_start=26
  _globals['_APPLICATION_MESSAGE']._serialized_end=101
  _globals['_PRESENTATION_MESSAGE']._serialized_start=103
  _globals['_PRESENTATION_MESSAGE']._serialized_end=225
  _globals['_SESSION_MESSAGE']._serialized_start=228
  _globals['_SESSION_MESSAGE']._serialized_end=612
# @@protoc_insertion_point(module_scope)
